/*
 * File: ert_main.c
 *
 * Code generated for Simulink model 'TMR_Model'.
 *
 * Generated By : Aditya N Rao
 * 
 * Model version                  : 1.1
 * Simulink Coder version         : 24.1 (R2024a) 19-Nov-2023
 * C/C++ source code generated on : Wed Jul 10 04:32:37 2024
 *
 * Target selection: ert.tlc
 * Embedded hardware selection: Atmel->AVR
 * Code generation objectives:
 *    1. Execution efficiency
 *    2. RAM efficiency
 */

#include <stddef.h>
#include <stdio.h>            
#include "TMR_Model.h"                 /* Model header file */

void rt_OneStep(void);

void rt_OneStep(void)
{
  static boolean_T OverrunFlag = false;

  /* Check for overrun */
  if (OverrunFlag) {
    rtmSetErrorStatus(rtM, "Overrun");
    return;
  }

  OverrunFlag = true;

  /* Step the model */
  TMR_Model_step();

  /* Indicate task complete */
  OverrunFlag = false;
}

int_T main(int_T argc, const char *argv[])
{
  /* Unused arguments */
  (void)(argc);
  (void)(argv);

  /* Initialize model */
  TMR_Model_initialize();

  fflush((NULL));

  while (rtmGetErrorStatus(rtM) == (NULL)) {
    /* The application continuously checks if TMR produces at least two equal outputs */
    /* for a given set of input */
    rt_OneStep();
  }

  return 0;
}
